name: Generate Pac-Man Contribution Graph

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pac-Man Graph
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: jonasbchat/pacman-contribution-graph@v1.0.0
        with:
          github_user_name: rahulrawat012
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Pac-Man graph to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
